In [1]:
import torch

In [3]:
torch.randint(3, (10,))

tensor([2, 1, 1, 2, 0, 0, 1, 1, 1, 2])

In [5]:
from omegaconf import OmegaConf

t = OmegaConf.create({
    'a': 1,
    'b': 2,
    'c': 3
})

In [7]:
t.a

1

In [2]:
import torch

In [5]:
t = torch.randn(1, 3)

In [6]:
t

tensor([[ 0.4336, -0.2284,  0.3392]])

In [7]:
t.expand(2, -1)

tensor([[ 0.4336, -0.2284,  0.3392],
        [ 0.4336, -0.2284,  0.3392]])

In [10]:
a = (1,3)

b, c =zip(*a)

TypeError: 'int' object is not iterable

In [ ]:
a, b =zip(*t)

ValueError: too many values to unpack (expected 2)

In [3]:
import os

file_list = [os.path.join('/home/datasets/coco', file_path) for file_path in os.listdir('/home/datasets/coco')]

In [4]:
file_list

['/home/datasets/coco/README.txt',
 '/home/datasets/coco/test-dev2017.txt',
 '/home/datasets/coco/val2017.txt',
 '/home/datasets/coco/images',
 '/home/datasets/coco/train2017.txt',
 '/home/datasets/coco/LICENSE',
 '/home/datasets/coco/labels',
 '/home/datasets/coco/annotations']

In [1]:
import torch

In [3]:
torch.arange(40).chunk(2,dim=-1)

(tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19]),
 tensor([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
         38, 39]))